<?
	$cnfg_sitecolor = "#9C1C2D"; //Main colour for the website
	$cnfg_title = "Time Management"; //Title of the website
	$cnfg_rpp = 10;
	$cnfg_pps = 20;
	$cnfg_time_from = "09:00"; //default start time for users/category
	$cnfg_time_to = "17:00"; //default finish time for users/category
	$cnfg_icon_size = "100"; //default icon size for users
	$cnfg_grid_size = "1024 X 768"; //default grid size for users
	$cnfg_urgency_importance_allocation_type = "Grade"; //default urgency importance allocation type (Grade or Segment)
	$cnfg_min_task = "2"; //default minimum task per segment
	$cnfg_default_zoom = "100"; //default zoom for users
	$cnfg_breakfast_from = "10:00"; //default breakfast start time for users
	$cnfg_breakfast_to = "10:15"; //default breakfast finish time for users
	$cnfg_lunch_from = "12:00"; //default lunch start time for users
	$cnfg_lunch_to = "12:30"; //default lunch finish time for users
	$cnfg_tea_from = "14:00"; //default tea start time for users
	$cnfg_tea_to = "14:15"; //default tea finish time for users
	$cnfg_hour_from = "0"; //start time for a day (0-23)
	$cnfg_hour_to = "23"; //end time for a day (0-23)
	$cnfg_weekdays = "sunday,monday,tuesday,wednesday,thursday,friday,saturday"; //weekdays
	$cnfg_breaktypes = "Morning Tea,Lunch,Afternoon Tea"; //break type no spaces allowed
	$cnfg_days_to_fit_task = "7"; //default days count for fitting task
	$cnfg_admin_email = "admin@vidtraining.com";
	$cnfg_urgent_important_measured_by = "numbers";
	$cnfg_max_tasks_per_segment = "30";
	$cnfg_event_max_days_google = "10"; //no of days from today for which event is downloaded from google
	include("globals/config_override.inc");
?>